import Head from "next/head"
import "../styles/globals.css"
import Navbar from "../components/Navbar"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <Head>
        <title>Next13 Tailwind Portfolio Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicons/favicon.ico" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/favicons/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicons/favicon.ico"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicons/favicon.ico"
        />
        <link rel="mask-icon" href="/favicons/safari-pinned-tab.png" />
      </Head>
      <body>
        <Navbar>
          <main className="text-xl">{children}</main>
        </Navbar>
        <footer>this is the footer</footer>
      </body>
    </html>
  )
}
